### ISSUE TITLE
Add support for gulp/grunt

### ISSUE THREAD

**Issue by claudiusararu** [proatwork/generator-magetwo-code#1]
Could you please also add support for gulp or grunt? Not everyone is using codekit. 
Ty 💋

**Comment by proatwork** [comment]
Soon...
* _rubs palms together_ *

**Comment by proatwork** [comment]
haha @claudiusararu

**Comment by claudiusararu** [comment]
almost 5 years later... @proatwork

**Comment by proatwork** [comment]
Fixed
